env:
  node: true
  browser: true
  commonjs: true
  es2020: true
  mocha: true
extends: ['eslint:recommended', 'google']
parserOptions:
  ecmaVersion: 12
rules:
  quotes: ['warn', 'single', 'avoid-escape']
  indent: ['error', 2]